### ISSUE TITLE
Shutdown via OS menu not working with script?

### ISSUE THREAD

**Issue by Garou24** [wimpysworld/argon1-ubuntu#2]
I have the argon for ubuntu script installed on my pi4 8gb model running Ubuntu MATE 20.04. The fans and power buttons function as expected and the same as they do when using my Raspberry OS 64 image except when doing a shutdown. When selecting shutdown from the menu in Ubuntu the system will power off, but the red status light will not turn off. The board does not seem to register the system in an off state. The system will not respond to the power button at this point and will not turn on. Unplugging the power is the only way to reset the system and allow the power button to function and turn the system back on.

Under Raspberry OS 64 selecting the shutdown option within the OS will shut down the Pi4 and the red light will turn off. Pressing the power button on the case will then turn the system back on as expected.

**Comment by flexiondotorg** [comment]
I think you are describing this - https://github.com/wimpysworld/argon1-ubuntu/blob/master/argon1-ubuntu#L111

I'd like to find a way to issue the correct signal based upon the model of Pi currently is use.

**Comment by tssva** [comment]
I submitted a PR to send the correct signal based upon which Pi model is in use; however, this doesn't resolve this issue. Further investigation reveals that the installed shutdown script never executes whether called because a shutdown from the OS menu or from the cli. The reason for this is that the script contains no shebang calling python3.
